// Sistema global de microcopy (Copy Final §27, APROVADO no Editorial Freeze 02/10/2026).
// Chaves reutilizáveis: nenhuma tela escreve a própria versão destas frases
// (§27.33). Strings simples porque também rodam em componentes de cliente.
// Mentoria (§27.21-23) fica com o fluxo da Mentoria.

export const MICRO = {
  carregando: {
    generico: "Só um instante…",
    conteudo: "Estamos carregando este conteúdo.",
    mapa: "Estamos organizando suas respostas.",
    resultado: "Estamos preparando seu resultado.",
    acesso: "Estamos preparando seu acesso.",
  },
  erro: {
    titulo: "Algo não saiu como esperado.",
    texto: "Não conseguimos concluir esta ação agora. Tente novamente em alguns instantes.",
    tentar: "Tentar novamente",
    voltar: "Voltar",
    persistente: "Se o problema continuar, entre em contato com a gente.",
    conexao: "Parece que a conexão foi interrompida. Verifique sua internet e tente novamente.",
  },
  form: {
    obrigatorio: "Este campo precisa ser preenchido.",
    nome: "Digite seu nome.",
    emailVazio: "Digite seu e-mail.",
    emailInvalido: "Digite um e-mail válido.",
    whatsapp: "Confira o número e tente novamente.",
    mensagem: "Conte brevemente como podemos ajudar.",
    falha: "Não conseguimos enviar agora. Seus dados não foram confirmados. Tente novamente.",
    enviado: "Enviado.",
    enviando: "Enviando…",
  },
  consentimento: {
    operacional: "Ao enviar, você autoriza o uso dos dados informados para responder a esta solicitação.",
    editorial: "Quero receber também ideias, conteúdos e novidades do EPIC247.",
    sensiveis:
      "Não envie informações médicas, psicológicas ou outros dados pessoais sensíveis que não sejam necessários para esta solicitação.",
  },
  mapa: {
    comecar: "Começar meu Mapa",
    fazerDimensao: (dimensao: string) => `Fazer meu Mapa de ${dimensao}`,
    entrada: "Responda a partir de como sua vida está hoje, não de como você gostaria que estivesse.",
    semCerto: "Não existem respostas certas ou erradas.",
    progresso: (x: number, total: number) => `Pergunta ${x} de ${total}`,
    continuar: "Continuar",
    voltar: "Voltar à pergunta anterior",
    depois: "Você pode continuar depois.",
    retomadaTitulo: "Você deixou um Mapa em andamento.",
    retomar: "Retomar meu Mapa",
    recomecar: "Começar novamente",
    recomecarConfirma: "Começar de novo apaga o progresso salvo deste Mapa. Quer continuar?",
    manter: "Manter meu progresso",
    processando: "Estamos organizando suas respostas.",
    pronto: "Seu Mapa está pronto.",
    introResultado: "Isto não define quem você é. Mostra onde pode existir mais fricção neste momento.",
    verResultado: "Ver meu resultado",
    proximoMovimento: "Ver meu próximo movimento",
  },
  resultadoIndisponivel: {
    titulo: "Não conseguimos abrir este resultado.",
    texto: "O link pode estar incorreto ou este resultado pode não estar mais disponível.",
    novo: "Fazer um novo Mapa",
    voltar: "Voltar para o EPIC247",
  },
  resultadoExistente: {
    titulo: "Você já tem um resultado para este Mapa.",
    ver: "Ver meu resultado",
    refazer: "Refazer o Mapa",
    refazerTexto: "Refazer cria uma nova leitura do seu momento atual.",
  },
  captura: {
    titulo: "Quer guardar este resultado?",
    texto: "Receba seu Mapa por e-mail e mantenha um caminho para voltar a ele depois.",
    disponivel:
      "Seu resultado já está disponível. Se quiser recebê-lo por e-mail e continuar sua jornada, informe seus dados abaixo.",
    cta: "Receber meu resultado",
    sucesso: "Pronto. Enviamos o caminho para o seu resultado.",
    processando: "Seu e-mail foi registrado. Estamos preparando o envio.",
  },
  checkout: {
    quero: (produto: string) => `Quero meu ${produto}`,
    levando: "Estamos levando você para o ambiente de pagamento.",
    kiwify: "O pagamento será concluído no checkout da Kiwify.",
    falha: "Não conseguimos abrir o pagamento agora. Tente novamente.",
    tentar: "Tentar pagamento novamente",
  },
  pagamento: {
    confirmadoTitulo: "Pagamento confirmado.",
    confirmadoTexto: "Recebemos a confirmação. Agora vamos preparar seu acesso.",
    plano: "Pagamento confirmado. Estamos preparando seu Plano EPIC 7 Dias.",
    kit: (dimensao: string) => `Pagamento confirmado. Seu Kit EPIC ${dimensao} está sendo liberado.`,
    protocolo: "Pagamento confirmado. Seu acesso ao Protocolo EPIC247 está sendo liberado.",
    acessar: "Acessar meu produto",
    pendenteTitulo: "Pagamento em processamento.",
    pendenteTexto:
      "Ainda não recebemos a confirmação final do pagamento. Assim que ela chegar, o acesso será liberado conforme a regra do produto.",
    verificar: "Verificar novamente",
    recusadoTitulo: "Não foi possível confirmar o pagamento.",
    recusadoTexto: "Revise os dados no checkout ou tente outra forma de pagamento disponível.",
    jaTemTitulo: "Você já tem acesso a este produto.",
    jaTemTexto: "Não precisa comprar novamente.",
    revertido: "Este acesso precisa ser revisado porque o pagamento associado à compra foi revertido.",
    suporte: "Falar com o suporte",
  },
  posCompra: {
    planoTitulo: "Seu próximo movimento começa aqui.",
    planoTexto: "Seu pagamento foi confirmado. Vamos usar as respostas válidas do seu Mapa para preparar o Plano EPIC 7 Dias.",
    planoPreparando: "Estamos preparando seu Plano.",
    planoPronto: "Seu Plano EPIC 7 Dias está pronto.",
    planoVer: "Ver meu Plano",
    kitTitulo: "Seu Kit está disponível.",
    kitTexto: (dimensao: string) =>
      `Você já pode aprofundar ${dimensao} com o Manual, Workbook e as ferramentas práticas do Kit.`,
    kitAcessar: "Acessar meu Kit",
    protocoloTitulo: "Bem-vindo ao Protocolo EPIC247.",
    protocoloTexto: "Seu acesso ao sistema das 10 dimensões está disponível.",
    protocoloAcessar: "Acessar o Protocolo",
    protocoloMicro: "Existe uma sequência recomendada, mas você pode começar pelo lugar que sua vida pede atenção agora.",
  },
  newsletter: {
    campo: "E-mail",
    cta: "Quero receber",
    sucesso: "Inscrição confirmada.",
    sucessoTexto: "Você passa a receber ideias, conteúdos e novidades do EPIC247 no e-mail informado.",
    jaInscrito: "Este e-mail já está inscrito.",
    erro: "Não conseguimos concluir sua inscrição agora. Tente novamente.",
  },
  descadastro: {
    titulo: "Você não receberá mais estes e-mails.",
    texto: "Seu descadastro foi registrado.",
    voltar: "Voltar para o EPIC247",
    retornar: "Quero voltar a receber",
  },
  contato: {
    sucesso: "Mensagem recebida.",
    sucessoTexto: "Obrigado por escrever. Sua mensagem foi registrada e seguirá para o assunto selecionado.",
    falha: "Não conseguimos enviar sua mensagem agora.",
    falhaTexto: "Revise os campos e tente novamente em alguns instantes.",
  },
  vazio: {
    titulo: "Ainda não há conteúdo publicado aqui.",
    texto: "Estamos construindo este espaço. Enquanto isso, você pode explorar outras ideias do EPIC247.",
    cta: "Explorar Ideias",
    semRelacionado: "Não encontramos outro conteúdo relacionado a este tema agora.",
  },
  naoEncontrada: {
    titulo: "Essa página não está aqui.",
    texto: "O endereço pode ter mudado ou o link pode estar incorreto.",
    voltar: "Voltar para o EPIC247",
    friccao: "Descobrir meu ponto de fricção",
  },
  erroServidor: {
    titulo: "Algo não funcionou do nosso lado.",
    texto: "Não conseguimos carregar esta página agora. Tente novamente em alguns instantes.",
    tentar: "Tentar novamente",
  },
  indisponivel: {
    titulo: "Este produto não está disponível para compra agora.",
    texto: "Você pode continuar explorando a dimensão ou escolher outro próximo passo.",
    voltar: (dimensao: string) => `Voltar para ${dimensao}`,
    explorar: "Explorar o EPIC247",
  },
  reconhecido: {
    acessar: (produto: string) => `Acessar meu ${produto}`,
    verResultado: "Ver meu resultado",
    retomar: "Retomar meu Mapa",
    protocolo: "Acessar meu Protocolo",
  },
} as const;
